# Generated by Django 5.1.7 on 2025-03-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateField()),
                ('paciente', models.TextField()),
                ('tipo', models.CharField(choices=[('1', 'Consulta'), ('2', 'Servicio'), ('3', 'Tratamiento'), ('4', 'Otro')], max_length=20)),
                ('medico', models.TextField()),
                ('numerocita', models.IntegerField()),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
            },
        ),
    ]
