# Generated by Django 5.1.7 on 2025-03-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitasApp', '0002_alter_cita_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
